### PR TITLE
Remove support for many non-standard fields in trips.txt

### PR DESCRIPTION
**Pull request by leonardehrenfried**
This removes many non-standard fields from trips.txt that are not part of the GTFS specification:

- routeShortName
- continuousDropOffMessage
- drtMaxTravelTime
- drtAdvanceBookMin
- drtDropOffMessage
- continuousPickupMessage
- continuousDropOffMessage

Heads up to @Heidebritta @jeffmaki @sheldonabrown These affect transformer strategies that you originally wrote.

### CODE REVIEW

**Comment by jeffmaki** [comment]
I'm no longer at CS, I don't think Heide or Sheldon are either, but just curious: these were all optional, why remove them?

**Comment by leonardehrenfried** [comment]
Because they are not part of the GTFS spec and I cannot find a proposal for them.

I would like to avoid a library with lots of fields that have no documentation and an unclear status.

All the latest experimental fields have an annotation with a link to the proposal.

**Comment by jeffmaki** [comment]
I get that, your call. If this context is useful, I think the fields were from an early draft of -Flex or -BookingRules, but the standard evolved since. I agree the code should be updated, it just seemed extreme to break things as the "fix", but I also see your POV re: somebody needs to be maintaining this stuff on the side of the app that will break. 

I have no horse in this race, just sharing. Thanks for the heads up.

**Comment by leonardehrenfried** [comment]
If you know someone that could provide context on these fields, could you tag them here?

I'm not dead set on removing them just wanting to do a bit of clean up.

In particular I would like to know what `routeShortName` on a trip is useful for. Isn't that duplicating information from the route?

**Comment by aaronbrethorst** [comment]
Before removing these fields, it may be worth sharing the forthcoming breaking changes with the onebusaway-developers mailing list just to give the users of this library a heads up in case it affects them.

**Comment by jeffmaki** [comment]
Yeah, you know, I don't know who's left at CS managing these projects anymore. Try rbarcham@camsys.com maybe? 

And my *guess*, though you might check with @novalis and/or the folks at TriMet is that certain routes might change mid-trip, and this was needed for that case. As you know, there's a lot of weird edge cases around the world on stuff like this.

I couldn't tell you who/where/why/when, and also acknowledge that may be non-standard and kicked back to the GTFS governance process. Just trying to help here?

**Comment by leonardehrenfried** [comment]
Understand the need for using non-standard field and do so occasionally myself.

If people show up and provide a link to a document I will not delete them, of course.

**Comment by Heidebritta** [comment]
Hi Leonard,

I just took a quick look back to see if I could provide any help on these
fields.
I think Jeff is right, a lot of the fields were added to try and support
flex. I can see them added back in 2017 by one of my former colleagues.

It looks like the field routeShortName has been there since 2011, well
before my time working on this.

I am no longer with CS and sadly, despite my efforts, not working in
transportation. Removing me from any OneBusAway responsibilities would be a
good idea.

Thank you,
Heide.
https://www.linkedin.com/in/heidebritta-frank-pmp-589428/

**Comment by sberkley** [comment]
Hi @leonardehrenfried. I'm Scott Berkley, a software engineer at Sound Transit. We use OBA and OBA modules and continue to work with the remaining employees at CS. We don't use any of these fields, so I don't mind this particular breaking change, but would love to stay in touch about future development. Hopefully I can even make some contributions to the project myself!

**Comment by leonardehrenfried** [comment]
Welcome, @sberkley. I would sure love to collaborate.

**Pull request merged**
